# Stage 1: Build HTML files with Marp CLI
FROM node:alpine AS marp

# Set the working directory for Marp CLI
WORKDIR /usr/src/app

# Copy Markdown files to the Marp CLI container
COPY README.md .

# Install the Marp CLI
RUN yarn add @marp-team/marp-cli

# Convert Markdown to HTML using Marp CLI
RUN npx @marp-team/marp-cli README.md

# Stage 2: Build React application
FROM node:alpine AS react

# Set the working directory for the React app
WORKDIR /usr/src/app

# Copy package.json and yarn.lock
COPY frontend/package.json frontend/yarn.lock /usr/src/app/

# Install dependencies
RUN yarn

# Copy the rest of the application code
COPY frontend /usr/src/app/

# Build the React application
RUN yarn run build

# Stage 3: Serve built files with Nginx
FROM nginx:alpine

# Copy HTML files generated by Marp CLI to the Nginx h`tml directory
COPY --from=marp /usr/src/app/README.html /usr/share/nginx/html/

# Copy built React files to the Nginx html directory
COPY --from=react /usr/src/app/dist /usr/share/nginx/html/

# Copy Nginx configuration file
COPY nginx.conf /etc/nginx/conf.d/default.conf
